"""Add CASCADE delete to trips.session_id FK

Revision ID: 343271af4abc
Revises: ba0632ce623d
Create Date: 2026-04-09 20:32:38.659090
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "343271af4abc"
down_revision: Union[str, None] = "ba0632ce623d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("trips_session_id_fkey"), "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("trips_session_id_fkey"),
        "trips",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("trips_session_id_fkey"), "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("trips_session_id_fkey"),
        "trips",
        "chat_sessions",
        ["session_id"],
        ["id"],
    )
    # ### end Alembic commands ###
