"""Change trips.session_id FK to SET NULL instead of CASCADE

Revision ID: 855aa2145a4c
Revises: 343271af4abc
Create Date: 2026-04-09 20:52:06.654430
"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "855aa2145a4c"
down_revision: Union[str, None] = "343271af4abc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("trips_session_id_fkey"), "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("trips_session_id_fkey"),
        "trips",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("trips_session_id_fkey"), "trips", type_="foreignkey")
    op.create_foreign_key(
        op.f("trips_session_id_fkey"),
        "trips",
        "chat_sessions",
        ["session_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
