"""add_cascade_delete_chat_session_messages

Revision ID: ebdfa012cc3d
Revises: dc09a00121a1
Create Date: 2026-04-09 06:59:59.557380
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ebdfa012cc3d"
down_revision: Union[str, None] = "dc09a00121a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("messages_session_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "chat_sessions", ["session_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("messages_session_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_session_id_fkey"),
        "messages",
        "chat_sessions",
        ["session_id"],
        ["id"],
    )
    # ### end Alembic commands ###
